### ISSUE TITLE
Support for Task Run as Job

### ISSUE THREAD

**Issue by stikkireddy** [Nike-Inc/brickflow#7] opened 2023-08-09 17:07 UTC
Task Type is: run_job_task

If run_job_task, indicates that this task must execute another job.

https://docs.databricks.com/api/workspace/jobs/create

Job managed by brickflow
```
wf = Workflow(...)

@wf.job_task
def run_job():
    from some_some_folder import wf
    return wf
```

Jobs not managed by brickflow
```
wf = Workflow(...)

@wf.job_task
def run_job():
    return Workflows.from_name("...")
```

**Comment by asingamaneni** [comment] 2023-11-16 22:42
Duplicate of #55, so closing this!

**Closed** 2023-11-16 22:42 UTC
Labels: good first issue
